language: python

python:
#  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev

sudo: false

virtualenv:
  system_site_packages: true

# addons:
#  apt:
#    packages:
#    - python3-dev
#    - gcc

install:
  - pip install -U pip
  - pip3 install -U setuptools
  - pip3 install coverage
  - pip3 install coveralls
#  # Python 3.2 does not have mock library built-in.
#  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip3 install mock; fi
  - python3 setup.py develop
  - python3 setup.py install

before_script:
  - python3 --version

script:
  - PYTHONPATH=. coverage3 run --branch --source=onedrive_d setup.py test

after_success:
  - coverage3 report -m
  - coveralls

notifications:
  email: false
