language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"

sudo: false

addons:
  apt:
    packages:
    - python3-dev

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install coverage
  - pip install coveralls
  - pip install mock
  - python3 setup.py install

before_script:
  - python3 --version

script:
  - coverage3 run --source=onedrive_d setup.py test

after_success:
  coveralls

